name: CD - Docker
on:
  release:
    types: 
      - published

jobs:
  docker-deploy:
    name: Update Docker Repository
    runs-on: ubuntu-latest

    steps:
    - name: Checkout SCCmecExtractor Repo
      uses: actions/checkout@v4

    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build new image and add to Docker
      uses: docker/build-push-action@v6
      with:
          context: .
          file: containers/Dockerfile
          push: true
          tags: |
            alisonmacfadyen/sccmecextractor:latest
            alisonmacfadyen/sccmecextractor:${{ github.ref_name }}