name: CD - Docker
on:
  release:
    types: 
      - published

jobs:
  docker-deploy:
    name: Update Docker Repository
    runs-on: ubuntu-latest

    steps:
    - name: Checkout SCCmecExtractor Repo
      uses: actions/checkout@v4

    - name: Build new image and add to Docker
      uses: docker/build-push-action@v6
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: alisonmacfadyen/sccmecextractor
        tag_with_ref: true
        tags: latest
        add_git_labels: true