name: CI - Test Install

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
    types: 
      - opened
      - edited
      - synchronized
    paths-ignore:
      - "README.md"

jobs:
  test-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: 'latest'
          environment-name: sccmecextractor
          environment-file: environment.yml
          create-args: python=3.10
          condarc: |
            channels:
              - conda-forge
              - bioconda
          init-shell: bash
          cache-environment: true
          cache-downloads: true
          post-cleanup: all
      - name: Install test dependencies
        run: |
          micromamba install -y -n sccmecextractor pytest pytest-cov pytest-dependency
      - name: Mamba info
        run: |
          micromamba run -n sccmecextractor micromamba info
          micromamba run -n sccmecextractor micromamba list
          printenv | sort
      - name: Install package
        run: |
          micromamba run -n sccmecextractor pip install --no-cache-dir -e .
      - name: Run PyTest
        run: |
          micromamba run -n sccmecextractor pytest
